/*
 * SendPost API
 *
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * API version: 1.0.0
 * Contact: hello@sendpost.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsConsumerStats struct {
	ConnectedTimestamp int64 `json:"connectedTimestamp,omitempty"`
	MessageCount int64 `json:"messageCount,omitempty"`
	MessagesFinished int64 `json:"messagesFinished,omitempty"`
	MessagesRecieved int64 `json:"messagesRecieved,omitempty"`
	MessagesRequeued int64 `json:"messagesRequeued,omitempty"`
}
