/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsInvitation struct {
	Id int64 `json:"Id,omitempty"`
	Role *ModelsMemberRole `json:"Role,omitempty"`
	Status *ModelsInvitationStatus `json:"Status,omitempty"`
	ToEmail string `json:"ToEmail,omitempty"`
	Created int64 `json:"created,omitempty"`
}
