/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSingleCleanedMail struct {
	Email string `json:"email,omitempty"`
	Error_ string `json:"error,omitempty"`
	Reason *ModelsValidationReason `json:"reason,omitempty"`
	Valid bool `json:"valid,omitempty"`
}
