/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEIncident struct {
	Author *ModelsIeMember `json:"author,omitempty"`
	Description string `json:"description,omitempty"`
	RelatedIP *ModelsIeip `json:"relatedIP,omitempty"`
	RelatedSubAccount *ModelsIeSubAccount `json:"relatedSubAccount,omitempty"`
	Status int64 `json:"status,omitempty"`
	Summary string `json:"summary,omitempty"`
	Tags []ModelsIeTag `json:"tags,omitempty"`
}
