/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEAccountMember struct {
	CompanyName string `json:"companyName,omitempty"`
	CurrentEmailServiceProvider string `json:"currentEmailServiceProvider,omitempty"`
	Industry string `json:"industry,omitempty"`
	Name string `json:"name,omitempty"`
	OnboardQAnswered bool `json:"onboardQAnswered,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	SendingVolumePerMonth string `json:"sendingVolumePerMonth,omitempty"`
	Uid string `json:"uid,omitempty"`
	VerifyEmail bool `json:"verifyEmail,omitempty"`
}
