/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSmtpAuth struct {
	Created int64 `json:"created,omitempty"`
	Id int64 `json:"id,omitempty"`
	Password string `json:"password,omitempty"`
	Updated int64 `json:"updated,omitempty"`
	Username string `json:"username,omitempty"`
}
