/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsEditorTokenResponse struct {
	Expires string `json:".expires,omitempty"`
	Issued string `json:".issued,omitempty"`
	AccessToken string `json:"access_token,omitempty"`
	AsclientId string `json:"as:client_id,omitempty"`
	Asregion string `json:"as:region,omitempty"`
	ExpiresIn int32 `json:"expires_in,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	TokenType string `json:"token_type,omitempty"`
	UserName string `json:"userName,omitempty"`
}
