/*
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * API version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBillingPortalSession struct {
	Created int64 `json:"created,omitempty"`
	Customer string `json:"customer,omitempty"`
	Id string `json:"id,omitempty"`
	Livemode bool `json:"livemode,omitempty"`
	Object string `json:"object,omitempty"`
	ReturnUrl string `json:"return_url,omitempty"`
	Url string `json:"url,omitempty"`
}
